### PR TITLE
Update/0.10.2

### PR DESCRIPTION
**Pull request by chrisguida**

### CODE REVIEW

**Comment by chrisguida** [comment]
This is blocked until there's an upstream fix

**Comment by chrisguida** [comment]
waiting on upstream https://github.com/ElementsProject/lightning/pull/4950

Or switch base image from alpine to debian

**Comment by ProofOfKeags** [comment]
you're already doing this but for documentation's sake, proceed with the debian approach in lieu of understanding wtf is wrong with the alpine build.

**Comment by chrisguida** [comment]
Proceeding with alpine, we just need to delete the tests: https://github.com/ElementsProject/lightning/pull/4950#issuecomment-993247798

**Comment by chrisguida** [comment]
Closing in favor of https://github.com/Start9Labs/c-lightning-wrapper/pull/21

**Pull request closed without merging**
